### ISSUE TITLE
Sort courses by relevance by default

### ISSUE THREAD

**Issue by Tuupertunut** [UH-StudentServices/coursepages#1]
#### The use case

Open courses.helsinki.fi, type a course name to the search field and press "show results".

#### Current behavior

The courses will be listed alphabetically by name.

#### Suggested behavior

The courses would be listed by relevance.

#### Why?

Because sorting by relevance tends to give much better search results.

**Comment by mikaelkundert** [comment]
Hi!
Thanks for the request, this actually have been in our backlog for quite some time.

There has been suprisingly much use for alphabetical order too, so we implemented now an conditional default.

When users type a keyword, it will now use relevance as default. Otherwise it will stick still with alphabetical order.

This should be now fixed by v1.119.
